In [20]:
import gym
import numpy as np
import random as random

In [21]:
#Erklær environment
env = gym.make('Taxi-v3')

#Initialize table with all zeros based on environment
Q = np.zeros([env.observation_space.n, env.action_space.n])
#Print out Q
print(env.observation_space.n, env.action_space.n)
print(Q)

500 6
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [22]:


GAMMA  = 0.9
LEARNING_RATE = 0.1 #learning rate

episode = 10001

EPSILON = 1
MAX_EPSILON=1.0
MIN_EPSILON=0.01

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

penalities=0

In [23]:
#Køre spillet igennem i x-episoder
for i in range(episode):

    #Reset miljøet inden vi går igang
    state = env.reset()
    penalites,reward = 0,0
    done = False
    
    #Vil bliver ved med at lave actions indtil spillet er slut (vundet/død)
    while not done:
        
        #Episilon-Greed metode bruges til at udvælge om action skal være baseret på Q-tabel eller random   
        exploration_rate_threshold = random.uniform(0, 1)    
        
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(Q[state,:]) 
        else:
            action = env.action_space.sample()
                    
        #Næste action udføres
        next_state,reward,done,info = env.step(action)
        
        #Q value bestemmes for næste state
        next_max = np.max(Q[next_state])
        
        #Q[S,A] udregnes
        Q[state,action] =  Q[state,action] + LEARNING_RATE * ( reward + GAMMA * next_max - Q[state,action])
        
        #s = s'
        state = next_state
        
        #Epsilon-greed algorime justeres
        exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
        
    
    #Funktion til at se hvor langt vi er.
    if i%100==0:
        clear_output(wait=True)
        print('Episode: {}'.format(i))
        
print('Training Finished..')

Episode: 10000
Training Finished..


In [24]:
Q


array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [-2.56833119, -2.5894744 , -3.07140421, -2.59393682,  1.62261467,
        -4.40032378],
       [-1.27765661, -1.82093062,  0.06881368, -1.82093062,  7.7147    ,
        -2.1926863 ],
       ...,
       [-1.12801184, -0.44253496, -1.04661746, -1.14129887, -1.99      ,
        -1.99      ],
       [-2.60299627, -2.6047407 , -2.59915724, -2.60173283, -2.9701    ,
        -2.9701    ],
       [-0.199     , -0.199     , -0.199     ,  7.96017646, -1.        ,
        -1.        ]])

In [25]:
penalites,r = 0,0

total_rewards, total_steps , total_penalities =0,0,0

for _ in range(episode):
    state = env.reset()
    steps , penalties , reward = 0,0,0
    
    done = False
    
    while not done:
        #env.render()
        action = np.argmax(Q[state])
        state,reward,done,info = env.step(action)
        
        
        if reward == -10:
            penalites+=1
        
        r += reward
        
        steps+=1
    
    total_rewards+=r
    total_steps+=steps
    total_penalities+=penalites
    
    
print('Results After {} episodes'.format(episode))
print('Average timestep per Episode :{}'.format(total_steps/episode))
print('Average Penalties per Episode : {}'.format(total_penalities/episode))
print('Average Rewards per Episode : {}'.format(total_rewards/episode))

Results After 10001 episodes
Average timestep per Episode :13.116088391160885
Average Penalties per Episode : 0.0
Average Rewards per Episode : 39542.26517348265
